### ISSUE TITLE
Cannot install to VSCode 1.63.2

### ISSUE THREAD

**Issue by rodionmel** [ErickSancho/vscode-specman-support#1]
Getting message "is not compatible with the current version".
Linux:
Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
VSCode:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 3.10.0-693.el7.x86_64

**Comment by ErickSancho** [comment]
Fix has been uploaded
